### ISSUE TITLE
Zadeh has no arm64 version available.

### ISSUE THREAD

**Issue by mseymour** [savetheclocktower/pulsar-ide-typescript-alpha#2]
Loading up the package in Pulsar on my M1 MacBook Pro results in an error. Looks like there needs to be an arm64 build for zadeh, which has been also mentioned here:

- https://github.com/atom-community/zadeh/issues/103
- https://github.com/pulsar-edit/pulsar/issues/580
- https://github.com/mjrodgers/pulsar-ide-python/issues/6

### Versions

**Pulsar**: 1.114.2024021615 arm64
**Electron**: 12.2.3
**OS**: macOS 14.2.1
**Thrown From**: [pulsar-ide-typescript-alpha](https://github.com/savetheclocktower/pulsar-ide-typescript-alpha) package 0.0.16

### Stack Trace

Failed to activate the pulsar-ide-typescript-alpha package

```
At No native build was found for platform=darwin arch=arm64 runtime=electron abi=87 uv=1 armv=8 libc=glibc node=14.16.0 electron=12.2.3
    loaded from: /Users/mark/.pulsar/packages/pulsar-ide-typescript-alpha/node_modules/zadeh


Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=87 uv=1 armv=8 libc=glibc node=14.16.0 electron=12.2.3
    loaded from: /Users/mark/.pulsar/packages/pulsar-ide-typescript-alpha/node_modules/zadeh

    at Function.load.resolve.load.path (/packages/pulsar-ide-typescript-alpha/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/packages/pulsar-ide-typescript-alpha/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at /packages/pulsar-ide-typescript-alpha/node_modules/zadeh/index.js:1:2743)
    at /packages/pulsar-ide-typescript-alpha/node_modules/zadeh/index.js:4:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/pulsar-ide-typescript-alpha/node_modules/@savetheclocktower/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:41:17)
    at /packages/pulsar-ide-typescript-alpha/node_modules/@savetheclocktower/atom-languageclient/build/lib/adapters/autocomplete-adapter.js:548:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/pulsar-ide-typescript-alpha/node_modules/@savetheclocktower/atom-languageclient/build/lib/auto-languageclient.js:45:45)
    at /packages/pulsar-ide-typescript-alpha/node_modules/@savetheclocktower/atom-languageclient/build/lib/auto-languageclient.js:1243:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
```

### Commands

```
```

### Non-Core Packages

```
atom-debug-ui 1.0.5 
atom-tailwindcss 0.9.0 
atom-typescript 14.4.0 
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
autocomplete-lua 0.9.2 
autocomplete-php 0.3.7 
busy-signal 2.0.1 
change-case 0.6.5 
Chromo-Color-Previews 1.8.3 
copy-line-number 0.2.0 
docblockr 0.14.2 
docker 0.8.0 
editorconfig 2.6.1 
emmet 2.4.3 
file-icons 2.1.47 
git-blame 1.8.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
hyperclick-love 0.6.0 
ide-docker 0.1.0 
ide-php 0.7.18 
ide-typescript 0.9.5 
intentions 2.1.1 
language-docker 1.1.8 
language-glsl 2.0.4 
language-lua 0.9.11 
language-svg 0.9.2 
linter 3.4.0 
linter-eslint-node 1.0.5 
linter-lua 2.0.0 
linter-luaparse 0.2.0 
linter-php 1.6.1 
linter-ui-default 3.4.1 
love-atom 3.1.8 
love-ide 0.19.1 
minimap 4.40.1 
minimap-bookmarks 0.4.6 
minimap-cursorline 1.0.5 
minimap-find-and-replace 5.0.9 
minimap-git-diff 4.3.6 
minimap-highlight-selected 4.6.6 
minimap-lens 0.8.2 
minimap-selection 4.5.5 
monokai-neon-syntax 0.0.1 
php-debug 0.3.5 
pretty-json 2.1.2 
pulsar-ide-typescript-alpha 0.0.16 
react 0.18.0 
react-snippets 2.0.0 
scroll-sync 0.2.4 
scss-snippets 0.6.0 
sort-lines 0.19.0 
tabs-to-spaces 1.0.5 
tool-bar 1.4.4 
trailing-spaces 0.4.0 
tsx-tags-autocomplete 0.1.0 
```

**Comment by savetheclocktower** [comment]
Yeah, until I figure out how to do so automatically — which might need to happen on the Pulsar side; we've discussed this a bit — something like [the workaround described in this comment](https://github.com/mjrodgers/pulsar-ide-python/issues/6#issuecomment-1948364963) is probably your best bet.

**Comment by savetheclocktower** [comment]
So as of version `0.1.1` of this package, published just a few minutes ago, there should no longer be a dependency on `zadeh`. I was able to change my fork of `atom-languageclient` to remove its (minimal) dependency on `zadeh` in favor of identical functionality available through Pulsar's own fuzzy-matcher available at `atom.ui.fuzzyMatcher`.

If you update the package and still find that you (somehow) have to build `zadeh`, let me know, and I can reopen this issue.
